### ISSUE TITLE
中文支持

### ISSUE THREAD

**Issue by chendingyan** [li-xin-yi/HK-journalist#1]
我不明白pandoc metadata的中文支持现在是怎么work的。
我现在把texlive和中文字体的相关包都装了，最后是在report function里面的arglist里加了一句
”-V mainfont:xxxxx(中文字体）“  pandoc command才能render中文。

**Comment by li-xin-yi** [comment]
如果已经指定了`documentclass`是`ctexbeamer`（注意放在首行），应该是不用再指定中文字体的。

需要指定中文字体的话也可以写在metadata里面指定`mainfont:xxxx`

可以给我看一下更详细的例子和报错情况吗，谢谢。

**Comment by chendingyan** [comment]
目前的情况是我不知道metadata在哪里制定，所以改了你的源代码。在代码里增加了指定字体。
比如我`pandoc  srs.md -o srs.pdf --latex-engine=xelatex -V mainfont='WenQuanYi Micro Hei Mono'`

**Comment by chendingyan** [comment]
目前的情况是我不知道metadata在哪里制定，所以改了你的源代码。在代码里增加了指定字体。
我最后在代码里执行的语句是
pandoc srs.md -o srs.pdf --latex-engine=xelatex -V mainfont='WenQuanYi Micro Hei Mono' 然后成功显示了中文。
如果没有改代码的话，pdf不会显示中文。所以我觉得应该是我不知道你所说的metadata在哪里导致的。

**Comment by li-xin-yi** [comment]
> 目前的情况是我不知道metadata在哪里制定，所以改了你的源代码。在代码里增加了指定字体。
> 我最后在代码里执行的语句是
> pandoc srs.md -o srs.pdf --latex-engine=xelatex -V mainfont='WenQuanYi Micro Hei Mono' 然后成功显示了中文。
> 如果没有改代码的话，pdf不会显示中文。所以我觉得应该是我不知道你所说的metadata在哪里导致的。

Markdown开头那个YAML block里面就可以写metadata，用三个`-`和正文隔开。举个例子：

```markdown
---
mainfont: WenQuanYi Micro Hei Mono
title: 随便什么标题
author: 张三
date: 2020年5月26日
---

# Section 1

## Subsection 1

balabala
```

**Comment by chendingyan** [comment]
It works!谢谢啦！
