### ISSUE TITLE
0.0.5版本

### ISSUE THREAD

**Issue by lvzheqi** [li-xin-yi/HK-journalist#2]
目前0.0.5版本貌似没有把configuration文件夹打包上去
<img width="492" alt="1590552210606_FAE0469A-1734-4BEC-8AD6-4ED6869D4249" src="https://user-images.githubusercontent.com/15264516/82976910-f516f780-a012-11ea-939b-67b50318c986.png">

导致文件生成不了。

**Comment by li-xin-yi** [comment]
感谢反馈。我确实没动过`setup.py`所以也不知道哪里出了问题没打包上去，现在新版本已经发布，`testpypi`上测试过没问题了，等会`pypi`更新了就可以直接用了。

再次感谢。

**Comment by lvzheqi** [comment]
好的呢，辛苦！
